name: The F.I.L.M Blog
favicon: null
layout_spectrum: 0.50447
typography_spectrum: 0.41339
title: The F.I.L.M Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffe4df'
    - '#acd3c7'
    - '#8a8681'
    - '#afaba6'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
